# Define variables.
prefix      ?= /usr/local
bindir       = $(prefix)/bin
binary_name  = container-compose
swift_product = container-compose
release_bin  = .build/release/$(swift_product)

# Default target: a release build.
.PHONY: all build release debug test test-json build-tests coverage clean install uninstall help version-stamp clean-version-stamp build-stamped

all: build

# Debug build for local development. Stamps BuildInfo.swift with the current
# git short SHA + `debug` build kind so `container-compose version` identifies
# the exact commit the binary was built from.
debug: version-stamp
	swift build --product $(swift_product)

# Release build that explicitly resets BuildInfo.swift to its empty default first
# so the running binary reports a clean marketing version. `make build` and
# `make release` both flow through this path.
build release: clean-version-stamp
	swift build -c release --product $(swift_product) --disable-sandbox

# Release-config build with the version stamp included. Useful for snapshot
# builds (CI nightlies, brew HEAD installs) that should look like a release
# binary but still identify the source commit. Use `make build` / `make release`
# for true tagged releases.
build-stamped: version-stamp
	swift build -c release --product $(swift_product) --disable-sandbox

# Overwrite Sources/Container-Compose/BuildInfo.swift with the current git
# short SHA + `snapshot` build kind. Idempotent — safe to re-run. Skipped
# silently when not in a git checkout (e.g. tarball install).
version-stamp:
	@SHA="$$(git rev-parse --short HEAD 2>/dev/null || echo)"; \
	DIRTY=""; \
	if [ -n "$$SHA" ] && ! git diff --quiet 2>/dev/null; then DIRTY=".dirty"; fi; \
	if [ -z "$$SHA" ]; then echo "version-stamp: not a git checkout, leaving BuildInfo.swift untouched"; exit 0; fi; \
	printf '%s\n' \
	  '//===----------------------------------------------------------------------===//' \
	  '// Auto-generated by `make version-stamp`. DO NOT COMMIT MODIFICATIONS HERE.' \
	  '// Run `make clean-version-stamp` (or `make release`) to restore the empty default.' \
	  '//===----------------------------------------------------------------------===//' \
	  '' \
	  'import Foundation' \
	  '' \
	  'public enum BuildInfo {' \
	  "    public static let gitCommit: String = \"$$SHA$$DIRTY\"" \
	  '    public static let buildKind: String = "snapshot"' \
	  '}' \
	  > Sources/Container-Compose/BuildInfo.swift; \
	echo "version-stamp: wrote BuildInfo.swift with gitCommit=$$SHA$$DIRTY"

# Restore Sources/Container-Compose/BuildInfo.swift to the empty release default.
# Used by `make build` and `make release` so tagged release builds never carry
# a stale local SHA.
clean-version-stamp:
	@git checkout -- Sources/Container-Compose/BuildInfo.swift 2>/dev/null && \
	  echo "clean-version-stamp: restored BuildInfo.swift from index" || \
	  echo "clean-version-stamp: BuildInfo.swift already at default (or no git index)"

# Compile both the executable and every test target without running them.
# Mirrors what CI does (`swift build --build-tests`) — useful as a fast
# check that the package still type-checks.
build-tests:
	swift build --build-tests

# Run the entire test suite. Dynamic tests skip themselves on hosts where
# Apple `container` isn't installed (see Tests/TestHelpers/RuntimeAvailability.swift),
# so this is safe to run on CI without the runtime.
test:
	swift test

# Run the static suite under swift-testing's event stream and emit a structured
# report. Useful for agent-driven test reading or CI parsing. Defaults to
# fast-feedback path: skipping the dynamic Apple-container target (use
# `make test` for the full run including dynamics).
#
# NOTE: --parallel intentionally NOT used. The static suite contains tests
# (ResourceArgsTests, LifecycleArgsTests, GpusBlkioTests) that `dup2` global
# STDOUT_FILENO to a Pipe to capture printed warnings; under --parallel they
# race on the shared FD and `readDataToEndOfFile()` hangs indefinitely.
#
# Exit code mirrors the report: 0 = all passed, 1 = any failed, 2 = no events.
test-json:
	rm -f .build/test-events.jsonl
	-swift test --skip Container-Compose-DynamicTests --experimental-event-stream-output .build/test-events.jsonl
	swift run test-report .build/test-events.jsonl --format json

# Regenerate coverage.json from the inline JSON in coverage.html.
coverage:
	bash scripts/regen-coverage.sh

clean:
	rm -rf .build

install: build
	install -d "$(bindir)"
	install "$(release_bin)" "$(bindir)/$(binary_name)"

uninstall:
	rm -f "$(bindir)/$(binary_name)"

help:
	@echo "Targets:"
	@echo "  build / release   Release build of $(binary_name)"
	@echo "  debug             Debug build of $(binary_name)"
	@echo "  build-tests       Compile tests without running (CI-equivalent)"
	@echo "  test              Run all tests (dynamic ones self-skip without Apple container)"
	@echo "  test-json         Run static tests + emit structured JSON report (skips dynamic; for agents/CI)"
	@echo "  coverage          Regenerate coverage.json from coverage.html"
	@echo "  clean             Remove .build/"
	@echo "  install           Build + install to \$$(bindir) (default $(bindir))"
	@echo "  uninstall         Remove the installed binary"
