//===----------------------------------------------------------------------===//
// Copyright © 2026 Morris Richman and the Container-Compose project authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

import AsyncHTTPClient
import Foundation
import NIOCore
import NIOPosix
import NIOSSL

// MARK: - DaemonClient

/// Lightweight probe client for `system status --address` on TCP/TLS targets.
///
/// Auto-trust policy for TLS:
/// 1. If `--cacert` is provided → add it as an additional trust root.
/// 2. Else if connecting to a localhost address AND `~/.container-compose/cert.pem`
///    exists → auto-trust the local cert (generated by `system generate-cert`).
/// 3. Else → system roots (suitable for production certs).
///
/// CHAOS-1359 (Phase 9 — TCP transport + TLS)
enum DaemonClient {

    // MARK: - ProbeResult

    enum ProbeResult: Sendable {
        /// The daemon responded to `GET /_ping` within the timeout.
        case alive(elapsedMs: Int)
        /// TCP connection succeeded but the response was unexpected.
        case unexpectedResponse(status: UInt)
        /// Connection or TLS handshake error.
        case error(String)
    }

    // MARK: - Default cert path

    static var defaultLocalCertPath: String {
        FileManager.default.homeDirectoryForCurrentUser
            .appending(path: ".container-compose")
            .appending(path: "cert.pem")
            .path
    }

    // MARK: - Probe

    /// Probe the daemon at `address` via HTTP(S), returning a `ProbeResult`.
    ///
    /// - Parameters:
    ///   - address: A `ListenAddress` (.tcp or .tls) to probe.
    ///   - cacertPath: Optional path to a CA certificate for TLS trust.
    static func probe(address: ListenAddress, cacertPath: String? = nil) async -> ProbeResult {
        let urlString: String
        switch address {
        case .unix:
            // Unix probes are handled by UnixSocketProbe — not this path
            return .error("DaemonClient only handles TCP/TLS targets")
        case .tcp(let h, let p):
            urlString = "http://\(h):\(p)/_ping"
        case .tls(let h, let p):
            urlString = "https://\(h):\(p)/_ping"
        }

        let tlsConfig: TLSConfiguration?
        if address.requiresTLS {
            tlsConfig = buildTLSConfig(address: address, cacertPath: cacertPath)
        } else {
            tlsConfig = nil
        }

        let config = HTTPClient.Configuration(tlsConfiguration: tlsConfig)
        // Force NIO-on-BSD-Sockets (MultiThreadedEventLoopGroup) so that NIOSSL's
        // additionalTrustRoots work correctly. macOS Network.framework (the default)
        // does not support custom trust roots and will reject self-signed certs even
        // when additionalTrustRoots is set.
        let eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)
        let client = HTTPClient(
            eventLoopGroupProvider: .shared(eventLoopGroup),
            configuration: config
        )

        let start = ContinuousClock().now
        do {
            defer {
                // Use shutdown() in a fire-and-forget task to avoid blocking the async context.
                // The ELG shutdown is dispatched to a background thread to avoid the
                // "unavailable from async context" restriction on syncShutdownGracefully.
                Task {
                    try? await client.shutdown()
                    DispatchQueue.global().async { try? eventLoopGroup.syncShutdownGracefully() }
                }
            }
            let request = HTTPClientRequest(url: urlString)
            let response = try await client.execute(request, timeout: .seconds(5))
            let elapsed = elapsedMs(since: start)
            if response.status.code == 200 {
                return .alive(elapsedMs: elapsed)
            } else {
                return .unexpectedResponse(status: response.status.code)
            }
        } catch {
            return .error(error.localizedDescription)
        }
    }

    // MARK: - TLS config builder

    private static func buildTLSConfig(address: ListenAddress, cacertPath: String?) -> TLSConfiguration {
        var tlsConfig = TLSConfiguration.makeClientConfiguration()

        // Determine trust anchor
        let resolvedCACert: String?
        if let explicit = cacertPath {
            resolvedCACert = explicit
        } else if address.isLocalhost && FileManager.default.fileExists(atPath: defaultLocalCertPath) {
            // Auto-trust local cert generated by `system generate-cert`
            resolvedCACert = defaultLocalCertPath
        } else {
            resolvedCACert = nil
        }

        if let caPath = resolvedCACert,
           let caCerts = try? NIOSSLCertificate.fromPEMFile(caPath) {
            // Add the CA as an additional trust root so the self-signed cert chains.
            // Keep the default .fullVerification — the generated cert includes a SAN for
            // "localhost" / "127.0.0.1" so hostname verification passes without relaxation.
            // NOTE: .noHostnameVerification is NOT supported on macOS with Network.framework
            // (AsyncHTTPClient precondition fails). additionalTrustRoots is sufficient.
            tlsConfig.additionalTrustRoots = [.certificates(caCerts)]
        }
        // else: system roots + full verification (default)

        return tlsConfig
    }

    // MARK: - Timing helper

    private static func elapsedMs(since start: ContinuousClock.Instant) -> Int {
        let duration = ContinuousClock().now - start
        let components = duration.components
        let ns = components.seconds * 1_000_000_000 + components.attoseconds / 1_000_000_000
        return max(1, Int((Double(ns) / 1_000_000.0).rounded()))
    }
}
