//===----------------------------------------------------------------------===//
// Copyright © 2026 Morris Richman and the Container-Compose project authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

import HTTPTypes
import Hummingbird

/// Stamps the Hummingbird-injected `context.id` onto every response as
/// `X-Request-Id`. No UUID generation is needed — Hummingbird already injects
/// a per-request `RequestID` (hex-encoded counter + random, see
/// `Application.swift:107` in `.build/checkouts/hummingbird`). This middleware
/// just exposes that pre-existing value in the response header so clients can
/// correlate log entries with `APIErrorEnvelope.requestId` fields.
///
/// Ordering: must be the FIRST middleware added so the header is present even
/// on error responses generated by later middleware layers.
public struct RequestIDHeaderMiddleware<Context: RequestContext>: RouterMiddleware {
    public init() {}

    public func handle(
        _ request: Request,
        context: Context,
        next: (Request, Context) async throws -> Response
    ) async throws -> Response {
        var response = try await next(request, context)
        let requestId = context.id.description
        response.headers[.xRequestId] = requestId
        return response
    }
}

// MARK: - X-Request-Id header name

public extension HTTPField.Name {
    /// `X-Request-Id` — non-standard but widely used for request correlation.
    /// Stamped by `RequestIDHeaderMiddleware` on every response; mirrors the
    /// `requestId` field in `APIErrorEnvelope` so log consumers can join them.
    static let xRequestId = Self("X-Request-Id")!
}
