//===----------------------------------------------------------------------===//
// Copyright © 2026 Container-Compose project authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

//
//  Compose+FlagsLoggingPassthrough.swift
//  Container-Compose
//
//  Compatibility shim for `Flags.Logging.passThroughCommands()`.
//
//  Historically this method was generated by the `@OptionGroupPassthrough`
//  macro carried by the `mcrich23/container` fork. After moving to upstream
//  `full-chaos/container` (which tracks `apple/container`), the macro is no
//  longer present, but `Flags.Logging` is a single-field struct so the
//  generated method collapses to a one-liner.
//
//  Keep this file in lockstep with the upstream `Flags.Logging` definition
//  (see `Sources/Services/ContainerAPIService/Client/Flags.swift` in the
//  `container` package). If new fields are added there, mirror them here.
//

import ContainerAPIClient

extension Flags.Logging {
    /// Re-emits this option group as argv suitable for passing to a child
    /// `container` invocation. Mirrors what `@OptionGroupPassthrough` would
    /// generate. Single field today: `--debug`.
    public func passThroughCommands() -> [String] {
        debug ? ["--debug"] : []
    }
}
